GalleryWeb/Controllers/Admins/ArtistsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GalleryDAL;
using GalleryDAL.Entities;

namespace GalleryWeb.Controllers
{
    public class ArtistsAdminController : Controller
    {
        private readonly GalleryDbContext _context;

        public ArtistsAdminController(GalleryDbContext context)
        {
            _context = context;
        }

        // GET: ArtistsAdmin
        public async Task<IActionResult> Index()
        {
            var galleryDbContext = _context.Artists.Include(a => a.City);
            return View(await galleryDbContext.ToListAsync());
        }

        // GET: ArtistsAdmin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .Include(a => a.City)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: ArtistsAdmin/Create
        public IActionResult Create()
        {
            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "Name");
            return View();
        }

        // POST: ArtistsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,LastName,Bday,Death,ArtDirection,Telephone,IdCity,Surname,Url,AddInfo,Id")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "Name", artist.IdCity);
            return View(artist);
        }

        // GET: ArtistsAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "Name", artist.IdCity);
            return View(artist);
        }

        // POST: ArtistsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,LastName,Bday,Death,ArtDirection,Telephone,IdCity,Surname,Url,AddInfo,Id")] Artist artist)
        {
            if (id != artist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCity"] = new SelectList(_context.Cities, "Id", "Name", artist.IdCity);
            return View(artist);
        }

        // GET: ArtistsAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .Include(a => a.City)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: ArtistsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.Id == id);
        }
    }
}

GalleryWeb/Controllers/Admins/PicturesAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GalleryDAL;
using GalleryDAL.Entities;

namespace GalleryWeb.Controllers
{
    public class PicturesAdminController : Controller
    {
        private readonly GalleryDbContext _context;

        public PicturesAdminController(GalleryDbContext context)
        {
            _context = context;
        }

        // GET: PicturesAdmin
        public async Task<IActionResult> Index()
        {
            var galleryDbContext = _context.Pictures.Include(p => p.Artist).Include(p => p.Technique);
            return View(await galleryDbContext.ToListAsync());
        }

        // GET: PicturesAdmin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var picture = await _context.Pictures
                .Include(p => p.Artist)
                .Include(p => p.Technique)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (picture == null)
            {
                return NotFound();
            }

            return View(picture);
        }

        // GET: PicturesAdmin/Create
        public IActionResult Create()
        {
            ViewData["IdArtist"] = new SelectList(_context.Artists, "Id", "Name");
            ViewData["IdTechnique"] = new SelectList(_context.Techniques, "Id", "Name");
            return View();
        }

        // POST: PicturesAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,CreateDate,Price,Genre,AddInfo,IdArtist,IdTechnique,Url,Id")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                _context.Add(picture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArtist"] = new SelectList(_context.Artists, "Id", "Name", picture.IdArtist);
            ViewData["IdTechnique"] = new SelectList(_context.Techniques, "Id", "Name", picture.IdTechnique);
            return View(picture);
        }

        // GET: PicturesAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var picture = await _context.Pictures.FindAsync(id);
            if (picture == null)
            {
                return NotFound();
            }
            ViewData["IdArtist"] = new SelectList(_context.Artists, "Id", "Name", picture.IdArtist);
            ViewData["IdTechnique"] = new SelectList(_context.Techniques, "Id", "Name", picture.IdTechnique);
            return View(picture);
        }

        // POST: PicturesAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,CreateDate,Price,Genre,AddInfo,IdArtist,IdTechnique,Url,Id")] Picture picture)
        {
            if (id != picture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(picture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PictureExists(picture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdArtist"] = new SelectList(_context.Artists, "Id", "Name", picture.IdArtist);
            ViewData["IdTechnique"] = new SelectList(_context.Techniques, "Id", "Name", picture.IdTechnique);
            return View(picture);
        }

        // GET: PicturesAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var picture = await _context.Pictures
                .Include(p => p.Artist)
                .Include(p => p.Technique)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (picture == null)
            {
                return NotFound();
            }

            return View(picture);
        }

        // POST: PicturesAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var picture = await _context.Pictures.FindAsync(id);
            _context.Pictures.Remove(picture);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PictureExists(int id)
        {
            return _context.Pictures.Any(e => e.Id == id);
        }
    }
}

GalleryWeb/Controllers/ArtistsController.cs
using GalleryBLL.Interfaces;
using GalleryWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GalleryWeb.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IArtistService artistsService;
        IPictureService pictureService;
        IHRService hRService;
        public ArtistsController(ILogger<HomeController> logger, IArtistService artistsService,
            IPictureService pictureService, IHRService hRService)
        {
            _logger = logger;
            this.artistsService = artistsService;
            this.pictureService = pictureService;
            this.hRService = hRService;
        }
        public IActionResult Artists()
        {
            Artists model = new Artists(artistsService.GetAllArtists().ToList(), hRService.GetAllCities().ToList(), hRService.GetAllCountries().ToList());
            return View(model);
        }
        public IActionResult ShowArtist(int artistId)
        {
            SingleArtist model = new SingleArtist(artistsService.GetArtistById(artistId),
                pictureService.GetAllPicsFromArtist(artistId), hRService.GetCityById((int)artistsService.GetArtistById(artistId).IdCity));
            return View(model);
        }
    }
}

GalleryWeb/Controllers/ExploreController.cs
using GalleryBLL.Interfaces;
using GalleryBLL.Models;
using GalleryWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GalleryWeb.Controllers
{
    public class ExploreController : Controller
    {
        private readonly ILogger<ExploreController> _logger;
        ICurrentExhibitionService currentExhibitionService;
        IExhibitionService exhibitionService;
        IPictureService pictureService;
        IArtistService artistService;
        IHRService hRService;
        public ExploreController(ILogger<ExploreController> logger,
            ICurrentExhibitionService currentExhibitionService, IExhibitionService exhibitionService,
            IPictureService pictureService, IArtistService artistService, IHRService hRService)
        {
            _logger = logger;
            this.currentExhibitionService = currentExhibitionService;
            this.exhibitionService = exhibitionService;
            this.pictureService = pictureService;
            this.artistService = artistService;
            this.hRService = hRService;
        }
        public IActionResult ShowCExhibition(int eId, int ceId)
        {
            SingleExh model = new SingleExh(exhibitionService.GetExhById(eId), currentExhibitionService.GetCurExhById(ceId), 
                currentExhibitionService.GetAllPicsFromExhibition(ceId), hRService.GetPlaceById(currentExhibitionService.GetCurExhById(ceId).IdExhPlace)
                , hRService.GetCityById(hRService.GetPlaceById(currentExhibitionService.GetCurExhById(ceId).IdExhPlace).IdCity));
            return View(model);
        }
        
        public IActionResult ShowPicture(int picId)
        {
            var pic = pictureService.GetPicById(picId);
            SinglePicture model = new SinglePicture(pic);

            model.Picture.Artist = artistService.GetArtistById(pic.IdArtist);
            model.Picture.Technique = pictureService.GetTechById(pic.IdTechnique);
            //var art = artistService.GetArtistById(pic.IdArtist);
            //var tech = pictureService.GetTechById(pic.IdTechnique);
            //SinglePicture model = new SinglePicture(pic, art, tech);
            return View(model);
        }
        public IActionResult Collections()
        {
            Pictures model = new Pictures(pictureService.GetAllPics().ToList(), 
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());
            return View(model);
        }
        public IActionResult SortAZ()
        {
            Pictures model = new Pictures(pictureService.GetAllPics(), 
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());            
            model.pics = pictureService.SortPicturesAZ(model.pics); 
            return View("Collections", model);
        }
        public IActionResult SortZA()
        {
            Pictures model = new Pictures(pictureService.GetAllPics(),
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());            
            model.pics = pictureService.SortPicturesZA(model.pics); 
            return View("Collections", model);
        }
        public IActionResult FilterByGenre(string genreName)
        {
            Pictures jopa = new Pictures(pictureService.FilterByGenre(pictureService.GetAllPics(), genreName), 
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());
            //model.pics = pictureService.FilterByGenre(model.pics, genreName); 
            return View("Collections", jopa);
        }
        public IActionResult FilterByTechnique(string genreName)
        {
            Pictures jopa = new Pictures(pictureService.FilterByGenre(pictureService.GetAllPics(), genreName), 
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());
            //model.pics = pictureService.FilterByGenre(model.pics, genreName); 
            return View("Collections", jopa);
        }
        public IActionResult FilterByArtist(string genreName)
        {
            Pictures jopa = new Pictures(pictureService.FilterByGenre(pictureService.GetAllPics(), genreName), 
                artistService.GetAllArtists().ToList(), pictureService.GetAllTechniqes().ToList());
            //model.pics = pictureService.FilterByGenre(model.pics, genreName); 
            return View("Collections", jopa);
        }

    }
}

GalleryWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<GalleryDAL.Entities.UserEntity> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - [ Gallery Web ]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css" rel="stylesheet" crossorigin="anonymous">

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="favicon.ico" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <link  href="~/css/site.css" rel="stylesheet"/>
</head>
<body>

    <!-- Navigation-->
    <!-- Page header-->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <h2><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GalleryWeb</a></h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Artists" asp-action="Artists">Artists</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Explore" asp-action="Collections">Collections</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a></li>
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Cart">Cart</a></li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        @if (signInManager.IsSignedIn(User))
                        {
                if (User.Identity.Name == "helen.fedchuk@gmail.com")
                {
                        <div class="collapse navbar-collapse" id="navbarText">
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Manage...
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownPortfolio">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="CurrentExhibitionsAdmin" asp-action="Index">Current Exhibitions</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="ExhibitedPictures" asp-action="Index">Exhibited pictures</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="ExhibitionsAdmin" asp-action="Index">Exhibitions pool</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="ArtistsAdmin" asp-action="Index">Artists</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="PicturesAdmin" asp-action="Index">All Pictures</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="EmployeesAdmin" asp-action="Index">Staff</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                }
                        
                         <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-item btn nav-link" style="width:auto">
                                        <h8>Logout @User.Identity.Name</h8>
                                    </button>
                                </form>
                         </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Account" asp-action="Register" class="navbar-brand">Register</a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Account" asp-action="Login" class="navbar-brand">Login</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Web Galley 2021</p></div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>*@


    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>