GalleryWeb/Controllers/Admins/CurrentExhibitionsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GalleryDAL;
using GalleryDAL.Entities;
using GalleryBLL.Interfaces;
using GalleryBLL.Models;
using GalleryWeb.Models;

namespace GalleryWeb.Controllers.Admins
{
    public class CurrentExhibitionsAdminController : Controller
    {
        private readonly GalleryDbContext _context;
        ICurrentExhibitionService currentExhibitionService;
        IExhibitionService exhibitionService;
        IHRService hRService;

        public CurrentExhibitionsAdminController(GalleryDbContext context, ICurrentExhibitionService currentExhibitionService, IExhibitionService exhibitionService, IHRService hRService)
        {
            _context = context;
            this.currentExhibitionService = currentExhibitionService;
            this.exhibitionService = exhibitionService;
            this.hRService = hRService;
        }

        // GET: CurrentExhibitions
        public async Task<IActionResult> Index()
        {
            //var galleryDbContext = _context.CurrentExhibitions.Include(c => c.Employee).Include(c => c.Exh).Include(c => c.ExhPlace);
            var list = currentExhibitionService.GetAllCurrentExhibitions().ToList();
            foreach (CurrentExhibitionModel c in list)
            {
                currentExhibitionService.CountEstimatePrice(c.Id);
                c.Employee = hRService.GetEmployeeById(c.IdEmployee);
                c.Exhibition = exhibitionService.GetExhById(c.IdExh);
                c.ExhibitPlace = hRService.GetPlaceById(c.IdExhPlace);
            }
            CEViewModel model = new CEViewModel(list);
            return View(model);
        }

        // GET: CurrentExhibitions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentExhibition = await _context.CurrentExhibitions
                .Include(c => c.Employee)
                .Include(c => c.Exh)
                .Include(c => c.ExhPlace)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (currentExhibition == null)
            {
                return NotFound();
            }

            return View(currentExhibition);
        }

        // GET: CurrentExhibitions/Create
        public IActionResult Create()
        {
            ViewData["IdEmployee"] = new SelectList(_context.Employees, "Id", "LastName");
            ViewData["IdExh"] = new SelectList(_context.Exhibitions, "Id", "Name");
            ViewData["IdExhPlace"] = new SelectList(_context.ExhibitPlaces, "Id", "Name");
            return View();
        }

        // POST: CurrentExhibitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEmployee,IdExh,IdExhPlace,DateBegin,DateEnd,maxTicketQuantity,EstimatedPrice,Tag,Id")] CurrentExhibition currentExhibition)
        {
            if (ModelState.IsValid)
            {
                _context.Add(currentExhibition);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmployee"] = new SelectList(_context.Employees, "Id", "LastName", currentExhibition.IdEmployee);
            ViewData["IdExh"] = new SelectList(_context.Exhibitions, "Id", "Name", currentExhibition.IdExh);
            ViewData["IdExhPlace"] = new SelectList(_context.ExhibitPlaces, "Id", "Name", currentExhibition.IdExhPlace);
            return View(currentExhibition);
        }

        // GET: CurrentExhibitions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentExhibition = await _context.CurrentExhibitions.FindAsync(id);
            if (currentExhibition == null)
            {
                return NotFound();
            }
            ViewData["IdEmployee"] = new SelectList(_context.Employees, "Id", "LastName", currentExhibition.IdEmployee);
            ViewData["IdExh"] = new SelectList(_context.Exhibitions, "Id", "Name", currentExhibition.IdExh);
            ViewData["IdExhPlace"] = new SelectList(_context.ExhibitPlaces, "Id", "Name", currentExhibition.IdExhPlace);
            return View(currentExhibition);
        }

        // POST: CurrentExhibitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEmployee,IdExh,IdExhPlace,DateBegin,DateEnd,maxTicketQuantity,EstimatedPrice,Tag,Id")] CurrentExhibition currentExhibition)
        {
            if (id != currentExhibition.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(currentExhibition);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CurrentExhibitionExists(currentExhibition.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEmployee"] = new SelectList(_context.Employees, "Id", "LastName", currentExhibition.IdEmployee);
            ViewData["IdExh"] = new SelectList(_context.Exhibitions, "Id", "Name", currentExhibition.IdExh);
            ViewData["IdExhPlace"] = new SelectList(_context.ExhibitPlaces, "Id", "Name", currentExhibition.IdExhPlace);
            return View(currentExhibition);
        }

        // GET: CurrentExhibitions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentExhibition = await _context.CurrentExhibitions
                .Include(c => c.Employee)
                .Include(c => c.Exh)
                .Include(c => c.ExhPlace)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (currentExhibition == null)
            {
                return NotFound();
            }

            return View(currentExhibition);
        }

        // POST: CurrentExhibitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var currentExhibition = await _context.CurrentExhibitions.FindAsync(id);
            _context.CurrentExhibitions.Remove(currentExhibition);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CurrentExhibitionExists(int id)
        {
            return _context.CurrentExhibitions.Any(e => e.Id == id);
        }
    }
}

GalleryWeb/Views/CurrentExhibitionsAdmin/Create.cshtml
@model GalleryDAL.Entities.CurrentExhibition

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CurrentExhibition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdEmployee" class="control-label"></label>
                <select asp-for="IdEmployee" class="form-control" asp-items="ViewBag.IdEmployee"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdExh" class="control-label"></label>
                <select asp-for="IdExh" class="form-control" asp-items="ViewBag.IdExh"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdExhPlace" class="control-label"></label>
                <select asp-for="IdExhPlace" class="form-control" asp-items="ViewBag.IdExhPlace"></select>
            </div>
            <div class="form-group">
                <label asp-for="maxTicketQuantity" class="control-label"></label>
                <input asp-for="maxTicketQuantity" class="form-control" />
                <span asp-validation-for="maxTicketQuantity" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="EstimatedPrice" />

            @*<div class="form-group">
                <label asp-for="EstimatedPrice" class="control-label"></label>
                <input asp-for="EstimatedPrice" class="form-control" />
                <span asp-validation-for="EstimatedPrice" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control"></input>
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GalleryWeb/Views/CurrentExhibitionsAdmin/Delete.cshtml
@model GalleryDAL.Entities.CurrentExhibition

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CurrentExhibition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateBegin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateBegin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maxTicketQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maxTicketQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exh.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExhPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExhPlace.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GalleryWeb/Views/CurrentExhibitionsAdmin/Details.cshtml
@model GalleryDAL.Entities.CurrentExhibition

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CurrentExhibition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateBegin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateBegin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maxTicketQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maxTicketQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exh.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExhPlace)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExhPlace.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GalleryWeb/Views/CurrentExhibitionsAdmin/Edit.cshtml
@model GalleryDAL.Entities.CurrentExhibition

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CurrentExhibition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdEmployee" class="control-label"></label>
                <select asp-for="IdEmployee" class="form-control" asp-items="ViewBag.IdEmployee"></select>
                <span asp-validation-for="IdEmployee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdExh" class="control-label"></label>
                <select asp-for="IdExh" class="form-control" asp-items="ViewBag.IdExh"></select>
                <span asp-validation-for="IdExh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdExhPlace" class="control-label"></label>
                <select asp-for="IdExhPlace" class="form-control" asp-items="ViewBag.IdExhPlace"></select>
                <span asp-validation-for="IdExhPlace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateBegin" class="control-label"></label>
                <input asp-for="DateBegin" class="form-control" />
                <span asp-validation-for="DateBegin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="maxTicketQuantity" class="control-label"></label>
                <input asp-for="maxTicketQuantity" class="form-control" />
                <span asp-validation-for="maxTicketQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedPrice" class="control-label"></label>
                <input asp-for="EstimatedPrice" class="form-control" />
                <span asp-validation-for="EstimatedPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <p></p>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GalleryWeb/Views/CurrentExhibitionsAdmin/Index.cshtml
@model GalleryWeb.Models.CEViewModel

@{
    ViewData["Title"] = "Overview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css" rel="stylesheet" crossorigin="anonymous">

<link href="~/css/buttons.css" rel="stylesheet" />
<p></p>
<h1>Overview</h1>

<div class="btn-1" role="button" style=" text-align: center">
    <a asp-controller="CurrentExhibitionsAdmin" asp-action="Create"><span>Create new</span></a>
</div>
<table id="table" class="table">
    <thead>
        <tr>
            <th>
                Date begin
            </th>
            <th>
                Date End)
            </th>
            <th>
                Current Ticket quantity
            </th>
            <th>
                Estimated price
                (based on pics)
            </th>
            <th>
                Status
            </th>
            <th>
                Employee
            </th>
            <th>
                Name
            </th>
            <th>
               Place
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ceContext)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateBegin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEnd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxTicketQuantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstimatedPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tag)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exhibition.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExhibitPlace.Id)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>